# Generated by Django 2.2.10 on 2020-02-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200212_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage',
            old_name='enforced_on_saturdays',
            new_name='enforced_on_weekends',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='enforced_on_sundays',
        ),
        migrations.AlterField(
            model_name='dayprobability',
            name='day_of_week',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='day_of_week',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=10),
        ),
    ]
