# Generated by Django 2.2.10 on 2020-02-18 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_park_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='park',
        ),
        migrations.AddField(
            model_name='park',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
