# Generated by Django 2.2.10 on 2020-02-19 17:25

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200218_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='garage',
        ),
        migrations.AddField(
            model_name='park',
            name='ticket',
            field=djongo.models.fields.EmbeddedField(blank=True, default=None, model_container=api.models.Ticket, null=True),
        ),
    ]
